# Generated by Django 3.1.5 on 2021-02-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='count',
            new_name='counts',
        ),
    ]
